name: Deploy Vue.js App to cPanel

on:
  push:
    branches:
      - main # Cambia a la rama que deseas monitorear para el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and build project
      run: |
        npm install
        npm run build

    - name: Clean server directory
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa usuario_cpanel@cpanel.example.com "rm -rf /home/usuario/public_html/*"

    - name: Deploy to cPanel
      uses: appleboy/scp-action@v0.2.1
      with:
        host: cpanel.example.com # Cambia por tu dominio o IP
        username: usuario_cpanel # Tu usuario de cPanel
        key: ${{ secrets.CPANEL_SSH_KEY }}
        target: /home/usuario/public_html/
        source: ./dist/
