on: 
  push:
    branches:
      - main
name: 🚀 Despliege website on push
jobs:
  web-deploy:
    name: 🎉 Despliege
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Install dependencies and build project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: dev.imaarica.cl
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist/
        server-dir: ./