name: Deploy Vue.js App to cPanel

on:
  push:
    branches:
      - main # Cambia a la rama que deseas monitorear para el despliegue

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and build project
      run: |
        npm install
        npm run build

    - name: Clean server directory
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa devima@cpanel.example.com "rm -rf /home/devima/public_html/*"

    - name: Deploy to cPanel
      uses: appleboy/scp-action@master
      with:
        host: dev.imaarica.cl # Cambia por tu dominio o IP
        username: devima # Tu usuario de cPanel
        key: ${{ secrets.CPANEL_SSH_KEY }}
        target: /home/devima/public_html/
        source: ./dist/
